### ISSUE TITLE
Cannot use `SCREENSHOT=30` with Squeak-Trunk

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/builderCI#75]
Known issue? Any way [here's the error](https://travis-ci.org/dalehenrich/builderCI/jobs/40585526#L170)

**Comment by krono** [comment]
Weird.
Probably @fniephaus can say something?

**Comment by fniephaus** [comment]
No worries. I will have a look into this this weekend.

**Comment by fniephaus** [comment]
Looks like it's working again for some reason:
https://travis-ci.org/dalehenrich/builderCI/jobs/46493714

I'm actually having troubles to reproduce the problem. But please let me know if it ever happens again!

**Comment by dalehenrich** [comment]
@fniephaus the screenshot code is [failing for squeak4.5](https://travis-ci.org/dalehenrich/builderCI/jobs/50115126#L1880):

```
STARTING xvfb
+export DISPLAY=:99.0
+DISPLAY=:99.0
+sh -e /etc/init.d/xvfb start
Starting virtual X frame buffer: Xvfb+[[ 1 != 0 ]]
+exit 1
+[[ 1 != 0 ]]
++basename ./testBuilderCI.sh
+echo 'ERROR: testBuilderCI.sh'
ERROR: testBuilderCI.sh
```

I added a `set -e` to several of the scripts, because I noticed that random expression failures were not triggering a test failure, which is not right ... the net of that is that `ST=Squeak-4.5 SCREENSHOT=30` gets the above error ... I'm going to remove the SCREENSHOT from the .travis.yml file until this is fixed...

Not a critical issue now that Squeak builds are green ... but if we do hit Squeak issues, we might want this to work again:)

I appreciate your help!

**Comment by fniephaus** [comment]
No worries. I still need to find out what's causing the problem with `xvfb`...

Interestingly, this build works just fine:
https://travis-ci.org/fniephaus/SwtDemo/jobs/49666267

It's not using your repo, but a fork which is just 12 commits behind `dalehenrich:master`:
https://github.com/HPI-SWA-Teaching/builderCI/

**Comment by fniephaus** [comment]
And it even works with your master:
https://travis-ci.org/fniephaus/SwtDemo/jobs/50169521

[![Screenshot](http://i.imgur.com/ngm9hCl.png)](https://travis-ci.org/fniephaus/SwtDemo/jobs/50169521)

**Comment by dalehenrich** [comment]
I'm getting a ['cannot open display' error message randomly for Squeak-4.5](https://travis-ci.org/dalehenrich/metacello-work/jobs/50991968#L297) ... if the error isn't related to screenshot mode then I'll open a separate bug ...

**Comment by dalehenrich** [comment]
@fniephaus 

Note that there are [two Squeak4.5 builds here](https://travis-ci.org/dalehenrich/metacello-work/builds/50991956) ... the first one fails with ['cannot open display'](https://travis-ci.org/dalehenrich/metacello-work/jobs/50991968)  and the [second one runs cleanly](https://travis-ci.org/dalehenrich/metacello-work/jobs/50991969), so it presumably got past the display opening? 

I kiled the jobs before any other squeak builds were done, so I don't know how far this failure goes...

**Comment by fniephaus** [comment]
Hey @dalehenrich,
Since screenshot mode is disabled in those builds, I'm afraid it's rather a problem related to #85.
I will have a look into this tomorrow...

**Comment by dalehenrich** [comment]
Okay submitted a new issue #86 ... closing this one
