### ISSUE TITLE
Connection refused: ftp.gemtalksystems.com

### ISSUE THREAD

**Issue by fniephaus** [dalehenrich/builderCI#99]
Hi @dalehenrich,

For some reason, GemStone builds fail, because Travis can't access `ftp.gemtalksystems.com`:
https://travis-ci.org/dalehenrich/builderCI/jobs/63062106#L104

I can access the FTP server, but the performance is rather slow (max. 64 KiB/s).
Any idea what's causing the problem?

Regards,
Fabio

**Comment by dalehenrich** [comment]
I am late to this party, but there may have been some updates to the ftp.gemtalksystems.com server that broke things temporarily (I seem to recall some issues, but not when they happened ... hitting from web browser but not from script is what I seem to recall) ... I don't think this is a persistent issue so I'l lclose this bug ... reopen or post new issue if this recurs ...

**Comment by fniephaus** [comment]
No worries. Just wanted you to double-check this. :smiley:
